[package]
name = "wasm-module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["cdylib"]
path = "src/core/mod.rs"

[[bin]]
name = "main"
path = "src/bin.rs"

[dependencies]
wasm-bindgen = "0.2.93"
